/// A single corrected command generated by a rule.
#[derive(Debug, Clone)]
pub struct CorrectedCommand {
    /// The corrected command string to execute
    pub script: String,

    /// Which rule produced this correction
    pub rule_name: &'static str,

    /// Sort priority (lower = shown first, higher = shown later)
    pub priority: i32,

    /// Optional human-readable description of what was fixed
    pub description: Option<String>,
}

impl CorrectedCommand {
    pub fn new(
        script: String,
        rule_name: &'static str,
        priority: i32,
        description: Option<String>,
    ) -> Self {
        Self {
            script,
            rule_name,
            priority,
            description,
        }
    }
}

impl std::hash::Hash for CorrectedCommand {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.script.hash(state);
    }
}

impl PartialEq for CorrectedCommand {
    fn eq(&self, other: &Self) -> bool {
        self.script == other.script
    }
}

impl Eq for CorrectedCommand {}

impl std::fmt::Display for CorrectedCommand {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.script)
    }
}
